steps:
  - label: "Step 1: Build in docker container"
    command: "go build -o hello ."
    artifact_paths: "./"
    plugins:
      - docker#v5.3.0:
          image: "golang:1.18.0"
          workdir: ./ #app
  # just in case the build is kinda big. lol
  - wait
  # block for the name
  - label: "Step 2: Block for the name"
    block: "Name"
    prompt: "Enter your name please."
    fields:
      - text: "Developer's name"
        key: "dev-name"
        required: true
        default: "John Doe"
  # download artifact into the tmp dir
  - label: "Step 3: Download artifact and run"
    command:
      - buildkite-agent artifact download "./hello ." \
      - chmod +x hello
      - ./hello $(buildkite-agent meta-data get dev-name)


